### ISSUE TITLE
Wrong date output

### ISSUE THREAD

**Issue by amirhosseinkh2515** [rghorbani/react-native-persian-calendar-picker#32]
After using onDateChange or other props for showing the current date , the output is Gregorian calendar for GMT +0000 time instead of Persian calendar 
![Screenshot_1556956677](https://user-images.githubusercontent.com/50260624/57176128-52209800-6e69-11e9-81d2-60990281ce5d.png)

**Comment by rghorbani** [comment]
@amirhosseinkh2515 Actually it's not wrong. We are outputting standard javascript date. The package is not responsible for time either (The reason for using GMT time is because we are using ISO date to avoid time differences between regions). You can use `moment-jalaali` to transform to jalaali date.
